spring:
  application:
    name: ops-demo-order-service

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
  info:
    git:
      mode: full